<?php 
 /* this is auto generated file */
 return [
    [
        'module_id' => 'note',
        'package_id' => null,
        'menu' => '',
        'parent_name' => '',
        'name' => 'note.note.detailActionMenu',
        'label' => null,
        'note' => null,
        'ordering' => 0,
        'is_deleted' => 0,
        'version' => 0,
        'as' => null,
        'testid' => null,
        'value' => null,
        'icon' => null,
        'to' => null,
        'is_active' => 1,
        'extra' => null
    ],
    [
        'module_id' => 'note',
        'package_id' => null,
        'menu' => '',
        'parent_name' => '',
        'name' => 'note.note.itemActionMenu',
        'label' => null,
        'note' => null,
        'ordering' => 0,
        'is_deleted' => 0,
        'version' => 0,
        'as' => null,
        'testid' => null,
        'value' => null,
        'icon' => null,
        'to' => null,
        'is_active' => 1,
        'extra' => null
    ],
    [
        'module_id' => 'note',
        'package_id' => null,
        'menu' => '',
        'parent_name' => '',
        'name' => 'note.sidebarMenu',
        'label' => null,
        'note' => null,
        'ordering' => 0,
        'is_deleted' => 0,
        'version' => 0,
        'as' => null,
        'testid' => null,
        'value' => null,
        'icon' => null,
        'to' => null,
        'is_active' => 1,
        'extra' => null
    ]
];
